services:
    web:
        build: .
        ports: 
            - "8501:8501"  # Host:Container
        volumes:
            - .:/app  # Link the current directory to the /app directory in the container
